# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: repo.treescale.com/jatcwang/just_bazel:3.0.0
        auth:
          username: jatcwang  # can specify string literal values
          password: $TREESCALE_PASSWORD  # or project environment variable reference
    environment:
      BAZEL_NUM_JOBS: "5"
    steps:
      - checkout
      # concat all BUILD files and WORKSPACE for cache key
      - run:
          name: "Set env vars for bazel"
          command: echo "CI_BRANCH=$CIRCLE_BRANCH" >> $BASH_ENV
      - run:
          name: "Calculate cache key"
          command: "find -type f -name BUILD -exec cat {} >> .circleci/cache_key \\; && cat WORKSPACE >> .circleci/cache_key"
      - restore_cache:
          keys:
            - v1-bazel-{{ checksum ".circleci/cache_key" }}
            - v1-bazel-
      - run:
          name: "Build & Test"
          command: "ci/build_test_changed.sh"
      - save_cache:
          key: v1-bazel-{{ checksum ".circleci/cache_key" }}
          paths:
            - ~/.cache/bazel
          when: always
